version: '3.8'

services:
  solid-dataspace-manager:
    image: son1i/solid-dataspace-manager:latest
    container_name: solid-dataspace-manager
    restart: unless-stopped
    expose:
      - "3001"
    networks:
      - solid-dataspace

  smart-city-urban-heat-monitoring:
    image: son1i/smart-city-urban-heat-monitoring:latest
    container_name: smart-city-urban-heat-monitoring
    restart: unless-stopped
    expose:
      - "4200"
    networks:
      - solid-dataspace

  semantic-data-catalog-backend:
    image: son1i/semantic-data-catalog-backend:latest
    container_name: semantic-data-catalog-backend
    restart: unless-stopped
    environment:
      BASE_URI: http://localhost
      CATALOG_NAME: "Semantic Data Catalog"
      CATALOG_DESCRIPTION: "Demonstrator"
      DATABASE_URL: mysql+pymysql://semantic_data_catalog:mNXZqSq4oK53Q7@db:3306/semantic_data_catalog
      RESET_DB: "true"
      RUN_POPULATE: "true"
      SMTP_HOST: "smtp.ionos.de"
      SMTP_PORT: 587
      SMTP_USER: "ionos@ionos.de"
      SMTP_PASS: "abc.123"
      EMAIL_FROM: "ionos@ionos.de"
    command: >
      bash -c "
      alembic upgrade head &&
      python populate.py &&
      uvicorn main:app --host 0.0.0.0 --port 8000
      "
    expose:
      - "8000"
    networks:
      - solid-dataspace
    depends_on:
      - db
      - semantic-data-catalog-fuseki

  semantic-data-catalog-frontend:
    image: son1i/semantic-data-catalog-frontend:latest
    container_name: semantic-data-catalog-frontend
    restart: unless-stopped
    environment:
      REACT_APP_OIDC_ISSUER: https://solidcommunity.net
      REACT_APP_REDIRECT_URL: http://localhost/semantic-data-catalog/
      REACT_APP_FOOTER_LOGOS: /assets/images/Logo_GesundesTal.png,/assets/images/Icon_GesundesTal.png
      REACT_APP_VERSION: "0.5.0"
    expose:
      - "5000"
    networks:
      - solid-dataspace
    depends_on:
      - semantic-data-catalog-backend

  db:
    image: mariadb:10.5
    container_name: db
    hostname: db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 8ED4iwZwPcwKPc
      MYSQL_DATABASE: semantic_data_catalog
      MYSQL_USER: semantic_data_catalog
      MYSQL_PASSWORD: mNXZqSq4oK53Q7
    ports:
      - "3306:3306"
    networks:
      - solid-dataspace
    volumes:
      - semantic_data_catalog_db_data:/var/lib/mysql

  semantic-data-catalog-fuseki:
    image: stain/jena-fuseki
    container_name: fuseki
    hostname: fuseki
    restart: unless-stopped
    environment:
      ADMIN_PASSWORD: admin
    ports:
      - "3030:3030"
    networks:
      - solid-dataspace
    volumes:
      - semantic_data_catalog_fuseki_data:/fuseki

  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    restart: unless-stopped
    environment:
      - NR_UI_HOST=0.0.0.0
      - NR_ADMIN_ROOT=/node-red
      - NR_NODE_ROOT=/node-red
    volumes:
      - ./settings.js:/data/settings.js
      - nodered-data:/data
    networks:
      - solid-dataspace  
    expose:
      - "1880"

  caddy:
    image: caddy:2
    container_name: reverse-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - solid-dataspace
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    depends_on:
      - solid-dataspace-manager
      - smart-city-urban-heat-monitoring
      - semantic-data-catalog-frontend
      - node-red

volumes:
  semantic_data_catalog_db_data:
  semantic_data_catalog_fuseki_data:
  nodered-data: 

networks:
  solid-dataspace: