version: '3.8'

services:
  solid-dataspace-manager:
    image: son1i/solid-dataspace-manager:latest
    container_name: solid-dataspace-manager
    restart: unless-stopped
    expose:
      - "3001"

  smart-city-urban-heat-monitoring:
    image: son1i/smart-city-urban-heat-monitoring:latest
    container_name: smart-city-urban-heat-monitoring
    restart: unless-stopped
    expose:
      - "4200"

  caddy:
    image: caddy:2
    container_name: reverse-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    depends_on:
      - solid-dataspace-manager
      - smart-city-urban-heat-monitoring
