# eldat/timber-event.properties



# Example of a more descriptive transaction ID but still containing the hash.
# Uncomment to apply this pattern:
#idpattern = %n_%.%s

action    = ADD
bizstep   = commissioning
